
services:
  db:
    image: mariadb:12.3.2
    container_name: language_school_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - db_data:/var/lib/mysql

volumes:
  db_data:
