db.url=jdbc:mariadb://localhost:3306/language_school

login.user=login
login.pass=login_password
segreteria.user=segreteria
segreteria.pass=segreteria_password
insegnante.user=insegnante
insegnante.pass=insegnante_password
